site_name: Person_Detection_And_Tracking module
site_url: https://github.com/ramp-eu/Person_Detection_And_Tracking
repo_url: https://github.com/ramp-eu/Person_Detection_And_Tracking
site_description: RAMP Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/doc/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - Home: 'index.md'
  - 'Getting Started' : 'getting-started.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'User Guide': 'usermanual.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'